---
abstract: 'Basis for simple applications'
author:
  - 'Kevin Mulholland <moodfarm@cpan.org>'
build_requires:
  Data::Printer: 0
  File::Slurp: 0
  Test::More: 0
  perl: 5.014
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Basis
requires:
  Exporter: 0
  File::Basename: 0
  File::Temp: 0
  Getopt::Long: 0
  IPC::Cmd: 0
  Moo: 0
  Path::Tiny: 0
  Try::Tiny: 0
  YAML: 0
  perl: 5.014
  strict: 0
  vars: 0
  warnings: 0
version: 0.1
